/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RepoRealtimeRouteImport } from './routes/repo-realtime'
import { Route as RepoOldRouteImport } from './routes/repo-old'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as GithubInstallationCallbackRouteImport } from './routes/github-installation-callback'
import { Route as GithubCallbackRouteImport } from './routes/github-callback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRealtimeRoute = RepoRealtimeRouteImport.update({
  id: '/repo-realtime',
  path: '/repo-realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOldRoute = RepoOldRouteImport.update({
  id: '/repo-old',
  path: '/repo-old',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubInstallationCallbackRoute =
  GithubInstallationCallbackRouteImport.update({
    id: '/github-installation-callback',
    path: '/github-installation-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github-callback',
  path: '/github-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/github-callback': typeof GithubCallbackRoute
  '/github-installation-callback': typeof GithubInstallationCallbackRoute
  '/repo': typeof RepoRoute
  '/repo-old': typeof RepoOldRoute
  '/repo-realtime': typeof RepoRealtimeRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/github-callback': typeof GithubCallbackRoute
  '/github-installation-callback': typeof GithubInstallationCallbackRoute
  '/repo': typeof RepoRoute
  '/repo-old': typeof RepoOldRoute
  '/repo-realtime': typeof RepoRealtimeRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/github-callback': typeof GithubCallbackRoute
  '/github-installation-callback': typeof GithubInstallationCallbackRoute
  '/repo': typeof RepoRoute
  '/repo-old': typeof RepoOldRoute
  '/repo-realtime': typeof RepoRealtimeRoute
  '/signin': typeof SigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/github-callback'
    | '/github-installation-callback'
    | '/repo'
    | '/repo-old'
    | '/repo-realtime'
    | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/github-callback'
    | '/github-installation-callback'
    | '/repo'
    | '/repo-old'
    | '/repo-realtime'
    | '/signin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/github-callback'
    | '/github-installation-callback'
    | '/repo'
    | '/repo-old'
    | '/repo-realtime'
    | '/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GithubCallbackRoute: typeof GithubCallbackRoute
  GithubInstallationCallbackRoute: typeof GithubInstallationCallbackRoute
  RepoRoute: typeof RepoRoute
  RepoOldRoute: typeof RepoOldRoute
  RepoRealtimeRoute: typeof RepoRealtimeRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-realtime': {
      id: '/repo-realtime'
      path: '/repo-realtime'
      fullPath: '/repo-realtime'
      preLoaderRoute: typeof RepoRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-old': {
      id: '/repo-old'
      path: '/repo-old'
      fullPath: '/repo-old'
      preLoaderRoute: typeof RepoOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-installation-callback': {
      id: '/github-installation-callback'
      path: '/github-installation-callback'
      fullPath: '/github-installation-callback'
      preLoaderRoute: typeof GithubInstallationCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-callback': {
      id: '/github-callback'
      path: '/github-callback'
      fullPath: '/github-callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GithubCallbackRoute: GithubCallbackRoute,
  GithubInstallationCallbackRoute: GithubInstallationCallbackRoute,
  RepoRoute: RepoRoute,
  RepoOldRoute: RepoOldRoute,
  RepoRealtimeRoute: RepoRealtimeRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
